/*    /index.html   200

[[redirects]]
    from = "/booking"
    to = "djluvaluva.com/booking"
    status = 301
    force = true
    query = {path = ":path"}
    conditions = {Language = ["en","es"], Country = ["US"]}

[[redirects]]
    from = "/contact"
    to = "djluvaluva.com/contact"
    status = 301
    force = true
    query = {path = ":path"}
    conditions = {Language = ["en","es"], Country = ["US"]}